version: "3.8"

services:
  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - ./promtail-local-config.yaml:/etc/promtail/config.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - loki

  echos:
    image: alpine
    command: /bin/sh -c "while true; do sleep 15 ;echo hello_world2; done"
    networks:
      - loki

networks:
  loki: